- hosts: vps2
  tasks:
    - include_vars: windows.yml
    - name: Kill tmux session
      command: /usr/bin/tmux kill-session
    - name: Update packages
      apt:
        upgrade: dist
      become: true
    - name: Start tmux session
      command: /usr/bin/tmux new-session -d
    - name: Start tmux windows
      command: /usr/bin/tmux new-window -n {{item.name}} '{{item.command}}'
      with_items: "{{windows}}"
