- include_vars:
    file: rutorrent.yml
    name: rutorrent_settings
  tags:
    - torrent
- name: Create data directory
  file:
    path: /var/data/{{ data_dir }}
    state: directory
    mode: 0755
    owner: 1000
    group: 1000
  tags:
    - data
    - torrent
- name: Clone the image
  git:
    repo: 'https://github.com/fxleblanc/rtorrent-docker'
    dest: /tmp/rtorrent-docker
  tags:
    - clone
    - torrent
- name: Build the docker image
  docker_image:
    name: fxleblanc/rtorrent
    path: /tmp/rtorrent-docker
    tag: 1.0
    buildargs:
      admin_pass: "{{ rutorrent_settings.admin_pass }}"
  tags:
    - image
    - torrent
- name: Start container
  docker_container:
    name: torrent-{{ instance_name }}
    image: fxleblanc/rtorrent:1.0
    ports:
      - "80:80"
      - "6881:6881"
      - "6881:6881/udp"
      - "51413:51413"
      - "51413:51413/udp"
    dns_servers:
      - 8.8.8.8
    volumes:
      - /var/data/{{ data_dir }}:/downloads
  tags:
    - container
    - torrent
